pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/adjune9811/Jenkins-Azure-TF.git'
                sh 'ls -la' // List files for debugging to confirm repo and structure
            }
        }
        stage('Terraform Init') {
            steps {
                script {
                    // Navigate to RG-Test directory and initialize Terraform
                    sh 'cd RG-Test && terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                    // Navigate to RG-Test directory and run terraform plan
                    sh 'cd RG-Test && terraform plan -out=tfplan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    // Navigate to RG-Test directory and apply the Terraform plan
                    sh 'cd RG-Test && terraform apply -auto-approve tfplan'
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline execution complete."
            cleanWs() // Cleanup workspace after the run
        }
    }
}
