pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the Terraform configuration from your Git repository on the main branch
                git branch: 'main', credentialsId: 'your-credentials-id', url: 'https://github.com/adjune9811/Jenkins-Azure-TF.git'
            }
        }
        stage('Terraform Init') {
            steps {
                script {
                    // Initialize Terraform to download providers and set up the working directory
                   // sh 'terraform init'
                 sh '''
                   cd terraform-aws-ec2-with-vpc
                   terraform init
                '''
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                    // Run Terraform plan to preview changes
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    // Apply the changes defined in the Terraform configuration
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
    post {
        always {
            // Optional: Cleanup stage
            echo "Pipeline execution complete."
        }
    }
}
